spring:
  datasource:
    url: jdbc:mysql:///xblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 585346
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  spring:
    servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 10MB


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息，默认为true
    web:
      exposure:
        include: '*'  #以web方式暴露